---
- name: "Block: Manage legacy APT sources (.list format)"
  when: pve_migrate_to_deb822
  block:
    - name: "Find legacy .list files"
      ansible.builtin.find:
        paths: /etc/apt/sources.list.d/
        patterns: "*.list"
      register: legacy_list_files

    - name: "Rename legacy .list files to .list.bak"
      ansible.builtin.command: "mv {{ item.path }} {{ item.path }}.bak"
      loop: "{{ legacy_list_files.files }}"
      when: legacy_list_files.files | length > 0
      args:
        creates: "{{ item.path }}.bak"

    - name: "Comment out entries in /etc/apt/sources.list"
      ansible.builtin.lineinfile:
        path: /etc/apt/sources.list
        regexp: '^\s*deb\s'
        line: '# \g<0>'
        backrefs: true
        state: present

- name: "Block: Configure Proxmox and Debian APT repositories (.sources format)"
  block:
    - name: "Ensure official Debian repositories are configured"
      ansible.builtin.template:
        src: debian.sources.j2
        dest: /etc/apt/sources.list.d/debian.sources
        owner: root
        group: root
        mode: '0644'
      notify: Update APT cache

    - name: "Ensure enterprise repository file is absent"
      ansible.builtin.file:
        path: "/etc/apt/sources.list.d/pve-enterprise.sources"
        state: absent
      when: pve_disable_enterprise_repo
      notify: Update APT cache

    - name: "Ensure no-subscription repository is enabled"
      ansible.builtin.template:
        src: pve-no-subscription.sources.j2
        dest: /etc/apt/sources.list.d/pve-no-subscription.sources
        owner: root
        group: root
        mode: '0644'
      when: pve_enable_no_subscription_repo
      notify: Update APT cache

    - name: "Ensure Ceph repository is configured"
      ansible.builtin.template:
        src: ceph.sources.j2
        dest: /etc/apt/sources.list.d/ceph.sources
        owner: root
        group: root
        mode: '0644'
      when: pve_add_ceph_repo
      notify: Update APT cache

    - name: "Ensure (disabled) pvetest repository is configured"
      ansible.builtin.template:
        src: pve-test.sources.j2
        dest: /etc/apt/sources.list.d/pve-test.sources
        owner: root
        group: root
        mode: '0644'
      when: pve_add_pvetest_repo
      notify: Update APT cache

- name: Flush handlers to apply APT cache update
  ansible.builtin.meta: flush_handlers