---
- name: "Update all packages to the latest version"
  when: pve_update_system
  ansible.builtin.apt:
    update_cache: yes
    upgrade: dist
    autoremove: yes

- name: "Reboot the server if configured"
  when: pve_reboot_if_needed
  ansible.builtin.reboot:
    msg: "Rebooting server after Proxmox post-install configuration."
    connect_timeout: 5
    reboot_timeout: 300
    pre_reboot_delay: 0
    post_reboot_delay: 30
    test_command: uptime